NCAR/geocat-comp

src/geocat/comp/_ncomp/ncomp.pyx
test/test_carrayify.py

Using this decorator on a function in ncomp.pyx will ensure that all of that function's numpy.ndarray arguments are C-contiguous in memory.
The decorator function iterates over each input argument, checks if the argument is an instance of numpy.ndarray, then checks if its CARRAY flag is set (meaning the C_CONTIGUOUS, ALIGNED, and BEHAVED flags are all True), and then calls numpy.ascontiguousarray() on the argument array and inserts the new contiguous array into the argument list in place of the original non-contiguous array.
This decorator uses functools.wraps to ensure docstrings of all wrapped functions are preserved.

Add carrayify decorator to Cython code

---

src/geocat/comp/__init__.py
src/geocat/comp/_ncomp/ncomp.pyx
test/test_linint2.py

Add @carrayify decorator to `_ncomp._linint2`.
Throw a warning in `_ncomp._linint2` for non-monotonic coord arrays.
Create CoordinateError, raise it in linint2. `CoordinateError`s should be raised when a GeoCAT-comp function is passed a NumPy array as an argument without a required coordinate array being passed separately.
If the fi argument passed to linint2 is not an xarray.DataArray, and either of xi or yi is not explicitly passed to linint2, then there are no valid coordinate arrays for linint2 to use, and a CoordinateError is raised.
Add new test cases to test_linint2.py
New tests handle non-contiguous input arrays (fixed by @carrayify) and non-monotonic coordinate arrays (_ncomp._linint2 now raises a warning, and a test case is used to assert that the warning is thrown).
Note that …

carrayify linint2

---

src/geocat/comp/_ncomp/ncomp.pyx

Use "libncomp" as the namespace of the NComp C API in our Cython code.
I'm planning on creating a new Array class in ncomp.pyx that has `.ncomp` and `.numpy` attributes, but the `.ncomp` attribute name is causing conflicts with other references to the `ncomp` namespace used to call C functions from NComp.

"cimport ncomp as libncomp" in ncomp.pyx

---

src/geocat/comp/_ncomp/ncomp.pxd
src/geocat/comp/_ncomp/ncomp.pyx

Created a new _ncomp.Array class to simplify the process of interacting with a NumPy and ncomp_array that refer to the same data.

Refactor cython arrays

---

.circleci/run-checks.sh

This PR reconfigures dependencies, which became necessary after geocat-comp vs geocat-ncomp separation.

Reconfigure dependencies

---

docs/conf.py
meta.yaml
setup.py

Closes #109 
In an effort to respond to above issue, this PR modifies `meta.yml` and other relevant files to fetch release version from this repo's tags instead of source code in `main` branch.

Conda builds from release tags and changed version settings

---

meta.yaml

This just bumps version to "2021.03.0" for new release

Bumped version number for new release

---

requirements.txt
src/geocat/comp/interp_hybrid_to_pressure.py
test/test_interp_hybrid_to_pressure.py

This PR applies a workaround to `interp_hybrid_to_pressure` function for the issue with `metpy`'s xarray interface:
DESCRIPTION: `metpy.interpolate.interpolate_1d` had "no implementation found for 'numpy.apply_along_axis'" error for cases where the input is `xarray.Dataarray` and has more than 3 dimensions (e.g. 4th dim of `time`).
The workaround used in this PR uses `dask.array.core.map_blocks` instead of `xarray.apply_ufunc` and auto-chunks input arrays (if unchunked) to ensure using only `Numpy` interface of `metpy.interpolate.interpolate_1d` (i.e. When call map_blocks with Dask array, it calls Numoy interface of metpy function).

Apply a Workaround for Metpy's Issue with 4D Xarray in interp_hybrid_to_sigma 

---

.github/workflows/ci.yml
INSTALLATION.md
build_envs/environment.yml
build_envs/upstream-dev-environment.yml
docs/conda_environment.yml
docs/installation.rst
meta.yaml
requirements.txt
src/geocat/comp/climatology.py
src/geocat/comp/skewt_params.py
test/test_skewt_params.py

The latest geocat-comp conda releases (v2021.8.0) has `cftime` as a dependency, but it isn't listed in `meta.yml` or the other build and documentation files. This PR addresses this issue.
Files to change:
In addition, this PR fixes a testing issue with `test_skewt_params.py`, which appeared after MetPy's 1.1.0 release.

Added `cftime` as a dependency

---

.readthedocs.yml
docs/conda_environment.yml

A "failed due to excessive memory" case started here similar to one we saw recently for GeoCAT-examples. 
I attempted to fix this one with mamba as well, and it seems to have worked. 
Please see RTD build [here](https://readthedocs.org/projects/geocat-comp/builds/15907422/).

Try mamba to fix RTD build failures

---

src/geocat/comp/interpolation.py
src/geocat/comp/polynomial.py
test/test_polynomial.py

Essentially fixes the build tests timing out issue through addressing "UserWarning: Passing an object to dask.array.from_array which is already a Dask collection. This can lead to unexpected behavior." in `interpolation.py`.
PR also fixes "np.float Deprecated" warnings in `meteorology.py` and `test_meteorology.py` files

Fix Build tests timing out issue

---

src/geocat/comp/meteorology.py

Addresses #206 
- replaces `xr.ufuncs.func` with `np.func`

remove deprecated xr.ufuncs

---

build_envs/docs.yml
docs/conf.py

Closes #271
- uses docs env file to make an editable local install
- adds a print statement to conf.py that prints the sys path at time of documentation generation for debugging purposes
- removes a sys path add that isn't needed with new pip install method

Make local install for docs better

---

.github/workflows/ci.yml
docs/index.rst

Closes #264
- removes ncar conda channel from ci environment sources
- adds a job to the ci that uses sphinx's `make linkcheck` to:
- check documentation generation
- check for any broken links

Documentation and Link Checker

---

.github/workflows/ci-release.yml

Addresses #290
- adds another workflow that checks that the lastest release is importable

Adding import nightly CI test

---

.github/workflows/upstream-dev-ci.yml
build_envs/upstream-dev-environment.yml

Closes #289 
- removes ncar channel from upstream environment file
- moves more packages to install from github through pip instead of conda releases

Expand upstream CI

---

src/geocat/comp/climatologies.py

Resolves #308 
Related: https://github.com/pydata/xarray/issues/7362
This PR removes `xr.set_options(keep_attrs=True)` from `climatology.py`. This was causing the bug described in the xarray issue above. This change will clear up the CI failures and will need to be followed by another RP that incorporates an optional argument of `keep_attrs=True` for the climatology functions affected by the change.

CI failures quick patch

---

src/geocat/comp/meteorology.py

Resolves #307 
Issue was not with the link itself, but rather python trying to open an ssl connection with an incompatible cryptography package (I think)
- removes http://www.osti.gov/scitech/servlets/purl/548871 and https://doi.org/10.2172/548871, replaces with https://journals.ametsoc.org/view/journals/apme/35/4/1520-0450_1996_035_0601_imfaos_2_0_co_2.xml

Resolve CI link-check issue

---

build_envs/docs.yml
build_envs/environment.yml
docs/user_api/index.rst
src/geocat/comp/meteorology.py
src/geocat/comp/skewt_params.py
test/test_meteorology.py

Closes #305 
This PR patches a bug with `meteorology.showalter_index` that was causing issues with our CI. In addition, the function has been deprecated in favor of directly using `metpy.calc.showalter_index`.

Fix pint bug in showalter_index and deprecate

---

.github/workflows/ci.yml
.github/workflows/upstream-dev-ci.yml
build_envs/environment.yml

Closes #324 
- adds explicit numba dependency to environment.yml
- pins numpy in environment.yml to <1.24
- adds conda list step to CI and Upstream CI workflows for debugging in the future
Notes:
- we should be able to remove this pin on our side with the next numba release, as they have pinned it on their side upstream

Pin numpy for numba compatibility

---

src/geocat/comp/climatologies.py
test/test_climatologies.py

Closes #314
I cannot test these functions with `np.ndarray` inputs since they don't yet explicitly support that data structure. As far as I can tell, the aggregation functions for `xarray.core.groupby` and `xarray.core.resample` objects are the only ones used in this file that have `keep_attrs` as an argument.
TODO from our discussion below:

Add `keep_attrs` to functions

---

docs/user_api/index.rst
src/geocat/comp/__init__.py
src/geocat/comp/climatologies.py
test/test_climatologies.py

Closes #265
This PR adds a new function called `climate_anomaly` which is meant to replace the old `anomaly` function. This replacement is happening because `anomaly` is based off of the older `climatology` which does not correctly weight monthly data. `climate_anomaly` relies on `climatology_average` and `calendar_average` which both correctly weight monthly data. `climate_anomaly` also has xarray attribute handling which `anomaly` did not have.
`anomaly` and `climatology` are both deprecated in this PR for future removal.

Replace and deprecate `anomaly`

---

.github/workflows/upstream-dev-ci.yml

- remove condition of only allowed to be run on NCAR/geocat-comp repo

Allow upstream-dev to run on forks

---

.github/workflows/upstream-dev-ci.yml
build_envs/upstream-dev-environment.yml

- re-arrange order of action to set up conda, install pip dependencies, then install conda dependencies
- remove pip installs from conda env file
- switch to using miniconda instead of mamba
- rename the upstream dev environment to be distinct from the development environment
- update to run on python 3.10 instead of 3.8
See passing upstream CI here: https://github.com/anissa111/geocat-comp/actions/runs/4049852058

Upstream CI

---

docs/internal_api/index.rst
docs/user_api/index.rst
src/geocat/comp/__init__.py
src/geocat/comp/gradient.py

While working on the comp release, I noticed that the gradient.py functions were not included on the website. This PR fixes that

Add gradient function documentation to website

---

docs/internal_api/index.rst
src/geocat/comp/gc_util.py
src/geocat/comp/meteorology.py

Closes #351 
- Creates a `util.py` to house this and other future utility functions
- creates `_generate_wrapper_docstring()` utility function that generates sets the docstring on a wrapper function based on the base function docstring, which:
- adds a caution admonition to the top of the docstring marking it as a wrapper function, 
- links the base function
- appends the original docstring
- makes a teeny edit on the delta_pressure docstring
**General**
**Functionality**
**Documentation**
- [N/A] Docstrings have updated with any function changes
- [N/A] User facing functions have been added to `docs/user_api/index.rst` under their module

Create a utility function to generate docstrings on wrapper functions

---

.github/workflows/pypi.yaml

- specify python 3.10 for pypi release action. Currently it's trying to build with 3.11, which messes with our geocat-f2py dependency
**General**
- 🤫 Make an issue if one doesn't already exist

specify python 3.10 for pypi build

---

.github/workflows/pypi.yaml

Related to #391 
See also: #393
- turns out I was right about not using 3.11 in the pypi release action, just not for the issue I was trying to solve 
Note: I'm just going to admin merge this since this exact change was approved yesterday and I don't want to bother anyone this late

Limit pypi build to 3.10

---

docs/release-notes.rst

* Support for numpy input types and lat/lon kwargs in gradient by @jukent and @pilotchute in #385
* Update PR template to include manual addition to release notes by @anissa111 in #397
**Full Changelog**: https://github.com/NCAR/geocat-comp/compare/v2023.03.2...v2023.05.0
Closes #407

Release notes for v2023.05.0

---

.github/workflows/ci-release.yml
.github/workflows/ci.yml
build_envs/docs.yml
build_envs/environment.yml
build_envs/upstream-dev-environment.yml
docs/release-notes.rst
setup.cfg

Closes #422
Fixes CI failures on main due to dropped support of 3.8 by dependencies and adds support for python 3.11
- removes python 3.8 from supported versions
- limits highest supported version to <=3.11
After this PR is merged:
- I will go into the repo settings and add the 3.11 tests to the required list
- Corresponding changes will need to be made in the feedstock repo at the time of the next release
**General**

Dropping support for python 3.8 and adding 3.11

---

.readthedocs.yml
README.md
build_envs/docs.yml
build_envs/environment.yml
build_envs/upstream-dev-environment.yml
docs/getting_started/overview.rst
docs/installation.rst
docs/release-notes.rst
docs/user_api/index.rst
geocat/comp/__init__.py
geocat/comp/deprecated.py
requirements.txt
setup.cfg

Closes #420
- removes geocat-f2py dependency
- removes references to geocat-f2py
- creates `deprecated.py` to house fake f2py deprecation functions that direct users to try installing geocat-f2py directly
Note: this will also require corresponding changes in the feedstock repo when the next release is being made
**General**

Remove f2py dependency

---

.github/workflows/ci.yml
docs/release-notes.rst

Closes #444 
- Fixes codecov coverage by using an editable install of geocat-comp
- Removed redundant namespace and coverage tests, combining them into one test run that outputs a coverage report
- Adds artifacts for test outputs
See [fixed coverage report](https://app.codecov.io/github/anissa111/geocat-comp/commit/cd380d02c0a14767561c8f9f2756b67ee176e075) on my fork.
**General**

Fix codecov coverage reports

---

.github/workflows/asv-benchmarking.yml
docs/release-notes.rst

Closes #472
To see this in action, see my [fork](https://github.com/anissa111/geocat-comp/commit/65b8ba280fcc0f402dbedcc6c8fd7ac5c8af16f2).
- Benchmarks run in [this action](https://github.com/anissa111/geocat-comp/actions/runs/6669934123/job/18128763915), producing [this commit](https://github.com/NCAR/geocat-comp-asv/commit/5dc6738e494c3594f06eb437daac6630e69fdc61) on NCAR/geocat-asv
- Then, I manually re-run the benchmarks in [this action](https://github.com/anissa111/geocat-comp/actions/runs/6670020074). It does not re-run the previously run benchmarks in the previous actions, and [fails here](https://github.com/anissa111/geocat-comp/actions/runs/6670020074/job/18129048254#step:8:1) on purpose.
In this PR, I made a couple changes from the proof of concept runs above:
- I've increased …

Connect ASV benchmarking to CI

---

build_envs/environment.yml
docs/release-notes.rst

Remove numpy version pin since it is no longer needed for numba. 
Interestingly it was only in the environment.yml file. 
Closes #510
**General**

Remove no longer need numpy version pin

---

docs/conf.py
docs/release-notes.rst

Closes #519
The docs error was not super helpful, but we just needed to add a corresponding `%s` to the second argument of our `extlinks` set up for sphinx 6+
**General**

Fix extlinks formatting

---

.github/workflows/asv-benchmarking.yml
.github/workflows/ci-release.yml
.github/workflows/ci.yml
.github/workflows/upstream-dev-ci.yml
docs/release-notes.rst

Adds a retry step around linkcheck and test commands
A reopen of #530
Depends on #528, #531
Closes #529 
See environment retry forced failure and secondary creation in [forked logs](https://github.com/anissa111/geocat-comp/actions/runs/7227528674/job/19695365028)
See retry action retrying (unsuccessfully, but still retrying anyway) in [these logs](https://github.com/NCAR/geocat-comp/actions/runs/7227015730/job/19693820844?pr=530)
**General**

Add retry step to linkcheck and CI

---

.github/workflows/pypi.yaml
docs/release-notes.rst

Closes #533 
This PR just removes the user and password from the pypi action, but I've also added the workflow/repo as a trusted publisher on PyPI
I'm not exactly sure how to test this, but I'm pretty sure this is correct based [these docs](https://github.com/pypa/gh-action-pypi-publish/tree/v1.8.11/?tab=readme-ov-file#trusted-publishing).
**General**

Switch to PyPI Trusted Publishing

---

.github/workflows/ci-release.yml
.github/workflows/ci.yml
README.md
build_envs/docs.yml
build_envs/environment.yml
docs/contrib.rst
docs/release-notes.rst
setup.cfg

Python 3.12 Support

---

MANIFEST.in
docs/release-notes.rst
geocat/__init__.py
setup.cfg

Closes #547, replaces #557
- Converts geocat-comp to use an implicit namespace set up
- removes `geocat/__init__.py`
- changes to `setup.cfg`
- Makes some additions to `MANIFEST.in` to avoid packaging everything in the top level directory (side note, might want to revisit flat vs src-layout)
NOTE: This will have to be duplicated over on `geocat-viz` before being included in a release on this repo (edit: see https://github.com/NCAR/geocat-viz/pull/220).
Resources:
- [Setuptools package discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html)
- [implicit namespace package guide](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages)
- [PEP420](https://peps.python.org/pep-0420/)
**General**

Update to implicit namespace package

---

.github/workflows/ci.yml
docs/release-notes.rst

Closes #565 
So, I'm not entirely sure how to test this because the failures only come from main on the NCAR/geocat-comp repo.
I followed this documentation from Codevoc: [Adding the Codecov Token](https://docs.codecov.com/docs/adding-the-codecov-token)
**General**

Add token to codecov upload

---

.github/workflows/ci-release.yml
.github/workflows/ci.yml
build_envs/docs.yml
build_envs/environment.yml
docs/release-notes.rst
setup.cfg

Drop Python 3.9 Support

---

docs/release-notes.rst
geocat/comp/interpolation.py

Refactors the helper function `_vertical_remap_extrap` to avoid problematic for loops over the vertical levels and addresses some warnings related to specification of chunks, dimension specification with `argmax`, and intentional interpolation out of bounds.    
While this seems to address the most significant issues in terms of performance / execution time, there's still some clean up to be done in `interp_hybrid_to_pressure` and it would be nice to have a benchmark to cover this.
I did also replicate the poor performance with a larger example on my laptop in addition to the HPC system. 
Closes #591 
**General**

Address performance and deprecations in interp_hybrid_to_pressure

---

build_envs/asv-bench.yml
build_envs/environment.yml
docs/release-notes.rst
requirements.txt
setup.cfg

Temporary fix for #598
So, due to a pip bug (see https://github.com/Unidata/cftime/issues/327), sometimes pre-release versions get installed, which is what's messing with our release tests. Since numpy 2.0 isn't actually released yet, I don't anticipate any problems with this pin until numpy 2.0 is fully released and generally compatible.
**General**

Pin numpy<2.0 for PyPI install issue

---

docs/release-notes.rst

Part of #601
I've also added a comment to the bottom of the release notes with a template for starting new release note sections with the commonly expected headers.
**General**

Update release notes for v2024.04.0

---

.github/workflows/asv-benchmarking.yml
build_envs/asv-bench.yml
docs/release-notes.rst

Removes ASV version pin and pin micromamba version for ASV workflow
Closes #555
Closes #607 (though we should log another issue or keep this open until we can unpin conda)
**General**

Removes ASV version pin and pin Conda version for ASV workflow

---

.github/workflows/asv-benchmarking.yml
build_envs/asv-bench.yml
docs/release-notes.rst

Re-pins ASV again and lists environment info
Relates to #555
**General**

Re-pin ASV again and list env info

---

.github/workflows/ci-release.yml
docs/release-notes.rst

Nothing was wrong with the windows release, thankfully, it was a problem stemming from trying the pip install in the same environment that the conda version had been uninstalled from.
Changes:
- splits conda and pypi releases into two separate jobs
- adds pre-install environment cacheing
See [action run on my fork](https://github.com/anissa111/geocat-comp/actions/runs/9488707858/job/26148264321)
Closes #627
**General**

Refactor ci-release.yml

---

.github/workflows/ci-release.yml
.github/workflows/ci.yml
.github/workflows/upstream-dev-ci.yml
docs/release-notes.rst

This PR adds a `micromamba-version: '1.5.10-0'` to the environment set up steps of:
- `.github/workflows/ci-release.yml`
- `.github/workflows/ci.yml`
- `.github/workflows/upstream-dev-ci.yml`
Note that this is not also done in the retry environment set up steps because we're specifically not downloading micromamba in those steps.
Along with this PR, I will also need to invalidate the existing caches to have this change work for workflows that have a cached environment (edit: done)
See [these logs](https://github.com/anissa111/geocat-comp/actions/runs/11024007886/job/30616398998) from my fork to see successful CI.
**General**
- [n/a] Link relevant issues, make one if none exist

Pinning micromamba for CI

---

docs/citation.rst
docs/index.rst
docs/release-notes.rst

Removes the broken link to the old GeoCAT website citation page and makes a few minor updates to the citation docs for clarity.
The old GeoCAT website citation page for reference: https://github.com/NCAR/GeoCAT/blob/gh-pages/pages/citation.md
At some point we might consider removing the examples on here and swapping them for a sample BibTex entry which is a bit more generic (i.e. not specific to a particular citation style) as well.    
Closes #665
**General**

update citation docs

---

build_envs/asv-bench.yml
build_envs/environment.yml
docs/release-notes.rst
requirements.txt
setup.cfg

Removes NumPy version pin leftover from environment issues when there was only a pre-release of NumPy 2.0 (see #600).
Closes #685
**General**

Remove NumPy version pin

---

.github/workflows/ci-release.yml
.github/workflows/ci.yml
build_envs/docs.yml
build_envs/environment.yml
docs/release-notes.rst
setup.cfg

Bumps Python version pins to allow for Python 3.13 installs and adds Python 3.13 to testing.
Notably this doesn't bump Python versions for things like ASV and Codecov - not sure if we want to do that now as well.  
It also does not drop support for Python 3.10.  This means our testing matrix will get larger.  If that's an issue, we might think about testing min / max versions or at least not all versions on all platforms.  Dropping support for 3.10 right now seems a little soon.
Closes #675
**General**

Python 3.13 support and testing

---

docs/release-notes.rst
geocat/comp/climatologies.py
test/test_climatologies.py

Minor changes to an internal helper function in climatologies borrowed from Xarray in order to support non-nanosecond datetime objects.  The alternative would be to user the corresponding function from Xarray, but it's a bit more complex now (spanning multiple modules) and still private API.  
Thankfully we don't have that much date/time handling code in comp at this point (we mostly rely on xarray and friends) so it should just be this change that's needed.
Added test coverage as well. 
Closes #682
**General**
**Testing**

Non nanosecond datetime tests

---

.github/workflows/ci.yml
build_envs/min-deps.yml
docs/release-notes.rst
geocat/comp/climatologies.py
test/test_climatologies.py

Adds a minimum dependency environment file and testing to CI and makes a few minor changes for backwards compatibility with earlier versions of Pandas and Xarray to climatology functions and associated testing.  I thought about separating those out into their own PR, but the changes are quite minor.
What's missing:
* documentation for users + devs
* minimum versions in our dependency specification
I'm open to adding these now, but wonder if it might make sense to hold off a bit in case we opt to make changes (e.g. include other packages, change versions, etc.).  Also, I'm not aware of specific limitations to our backward compatibility so these would just be the limits of what we're testing.
Closes #697
**General**

Minimum dependency version testing and backwards compatibility

---

docs/release-notes.rst

Updates release notes, adds a point about removing `chunk_size` param being a breaking change, adds sphinx linking to referenced functions
Part of #703 
**General**
- [n/a] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the upcoming release.

Update release notes for v2025.03.0

---

docs/release-notes.rst
geocat/comp/climatologies.py
test/test_climatologies.py

Does the following:
* Adapts `_calculate_center_of_time_bounds` to ensure compatibility with CFTime and Datetime objects for climatology functions
* Adds test coverage for the above
* Updates related functions to minimize deprecation warnings
Closes #692
**General**
**Testing**

Ensure compatibility with CFTime and Datetime objects for climatology functions

---

docs/release-notes.rst
geocat/comp/meteorology.py

Updates the `delta_pressure` docstrings to clarify that thickness is here is referring to the difference in pressure rather than e.g. height between pressure levels.
Closes #635
**General**

Update delta_pressure docs

---

.github/workflows/asv-benchmarking.yml
benchmarks/asv.conf.json
build_envs/asv-bench.yml
docs/release-notes.rst

This PR:
- unpins asv
- adds `python=3.13` to the test matrix
- bumps up the farthest back-run commit to v2024.04.0 from v2023.02.0 to limit the amout of commits that newly-added benchmarks will be tried over
The bulk of work on this PR was actually verifying it was working from my fork. Here's how I (eventually) confirmed that the asv unpin and build update were working as expected:
- [Successful run](https://github.com/anissa111/geocat-comp/actions/runs/14766054730/job/41457621756) on my fork
- [Diff of branch](https://github.com/NCAR/geocat-comp/compare/main...anissa111:asv_update?expand=1) with successful run from my fork. Note that there are a couple of differences to allow for testing from my fork in `.github/workflows/asv-benchmarking.yml`
Closes #611
**General**

ASV Update

---

docs/release-notes.rst
geocat/comp/meteorology.py

Fix equation reference for `psychrometric_constant` in geocat-comp (and eventually in associated place in NCL documentation)
Referenced corrected within the code to [Equation 8](https://github.com/NCAR/geocat-comp/blob/55efd3826344161642d3452581af975809dda35a/geocat/comp/meteorology.py#L1618), but not in the documentation
Closes #721
**General**

Correct `psychrometric_constant` references

---

docs/release-notes.rst
geocat/comp/interpolation.py

Adds a note to the `interp_hybrid_to_pressure` docstring with info regarding how to adapt the function for use with an alternate hybrid-sigma pressure formulation.
Closes #689
**General**

Add note to `interp_hybrid_to_pressure` docs

---

docs/release-notes.rst
geocat/comp/meteorology.py
test/test_meteorology.py

Changes near surface thickness calculations in `delta_pressure` to be consistent with NCL (i.e. based upon the midpoints).
Adds test coverage.
And reminded me we could probably use to optimize this code.  
Closes #725
**General**

Delta pressure near surface thickness bugfix

---

docs/release-notes.rst
geocat/comp/climatologies.py
test/test_stats.py

Replaces deprecated `xarray.cftime_range` with `xarray.date_range`.
If I remember correctly, I did a bit of this before in some of the climatology PRs, but I must have missed this elsewhere in the code.
Closes #738
**General**

Replace deprecated `xarray.cftime_range` with `xarray.date_range`

---

.pre-commit-config.yaml

Reverts the blackdoc version for pre-commit to avoid the issue causing a check to fail in #768.
Ideally we'd more fully diagnose this issue and report upstream, but I haven't made it that far yet and this will keep things working for the time being
**General**

Revert blackdoc version in pre-commit config
