NCAR/geocat-comp

docs/_static/scripts/examples/matplotlib/mpl_linint2.ipynb
docs/_static/scripts/examples/matplotlib/mpl_linint2.py

Issue: https://github.com/NCAR/geocat-comp/issues/35
1. Thanks @abrammer, addressed issues with colorbar and contours
2. Switched from using matplotlib.contourf to xdarray.contourf for better handling
3. Tweaked the resultant grid to be coarser to make the plot (a) more obvious of the regredding technique and (b) resemble NCL example.

Linint2 Colorbar/contours

---

src/geocat/comp/__init__.py
src/geocat/comp/_ncomp/ncomp.pxd
src/geocat/comp/_ncomp/ncomp.pyx
test/test_moc_globe_atl.py

This pull request adds `moc_globe_atl` function of NCL into GeoCAT-comp. 
7 different test cases have been written to test if output data types, dimensions, and contents are correct for inputs with varying data types as well as user-defined or NaN missing value inputs. All test cases pass successfully.

Moc globe atl

---

docs/user_api/index.rst
src/geocat/comp/__init__.py
src/geocat/comp/_ncomp.pyx
src/geocat/comp/libncomp.pxd
test/test_rcm2points.py

rcm2points

---

docs/user_api/index.rst
src/geocat/comp/__init__.py
src/geocat/comp/_ncomp.pyx
src/geocat/comp/libncomp.pxd
test/test_dpres_plevel.py

Infrastructure for dpres_plevel

dpres plevel

---

docs/user_api/index.rst
src/geocat/comp/__init__.py
src/geocat/comp/_ncomp.pyx
src/geocat/comp/libncomp.pxd
test/test_dpres_plevel.py
test/test_grid2triple.py
test/test_triple2grid.py

triple2grid

---

src/geocat/comp/__init__.py
src/geocat/comp/polynomial.py
test/test_import.py
test/test_polynomial.py

Adds dtrend
+ Document/examples for ndpolyfit/ndpolyval/dtrend.

Dtrend + More

---

.github/workflows/actions.yml
.github/workflows/main.yml
docs/_static/scripts/examples/comp_only/example_moc_globe_atl.py
docs/_static/scripts/examples/matplotlib/mpl_linint2.py
docs/_static/scripts/examples/matplotlib/mpl_linint2points.py
docs/conf.py
setup.py
src/geocat/comp/__init__.py
src/geocat/comp/month_to_season.py
src/geocat/comp/polynomial.py
test/test_month_to_season.py
test/test_polynomial.py

Looking at switch to yapf, it's google maintained and provides better formatting options than autopep8.

GitHub actions

---

CONTRIBUTING.md
INSTALLATION.md
README.md

It is a fix to latest contributor updates on the documentation

Fixed broken URLs as well as added URLs for some dependencies

---

src/geocat/comp/__init__.py
src/geocat/comp/dewtemp.py
src/geocat/comp/relhum.py
test/test_relhum.py

- adds wrappers for relhum_water and relhum_ice
- fixes typo in relhum_water
- adds basic tests for relhum_water and relhum_ice
- removes unnecessary alias for dewtemp

Relhum release prep

---

CONTRIBUTING.md
INSTALLATION.md
README.md
docs/conf.py
setup.py
src/geocat/comp/climatology.py
src/geocat/comp/eofunc.py
test/test_climatology.py
test/test_eofunc.py
test/test_relhum.py

Several docs are updated to reflect the deprecation of GeoCAT-ncomp and the integration of GeoCAT-f2py.
Additional steps are added to CONTRIBUTING.md under "Adding new functions to the Geocat-comp repo" title to reflect the whole process for adding a new function.

Repo-specific documentation update for GeoCAT-f2py vs GeoCAT-ncomp

---

INSTALLATION.md

Slight paraphrasing to INSTALLATION.md

Docs update

---

README.md
build_envs/environment.yml
docs/citation.rst
docs/index.rst

Add citation info README

---

meta.yaml

version bump

---

meta.yaml

 version bump for june

---

src/geocat/comp/fourier_filters.py

bugfix for certain edge cases

---

docs/internal_api/index.rst
meta.yaml
src/geocat/comp/crop.py
src/geocat/comp/dewtemp.py
src/geocat/comp/heat_index.py
src/geocat/comp/relhum.py
test/test_crop.py
test/test_dewtemp.py
test/test_heat_index.py
test/test_relhum.py

Addresses #159
Functions to be addressed:

Rewrite S@S functions to be compatible with dask lazy compute

---

meta.yaml
src/geocat/comp/fourier_filters.py

 july continuous release

---

meta.yaml

version bump august

---

meta.yaml

version bump for september release

---

docs/internal_api/index.rst

- _relhum_ice added to internal api
- _relhum_water added to internal API
Adds these functions to internal documentation so that they can be included as related functions on #186

Add _relhum_ice and _relhum_water to internal api

---

docs/user_api/index.rst
meta.yaml
requirements.txt
src/geocat/comp/__init__.py
src/geocat/comp/spherical.py
test/test_spherical.py

Initial pull request for spherical.py and test_spherical.py

Spherical_harmonics functions

---

.github/workflows/ci.yml
meta.yaml

March continuous release

---

meta.yaml

Build number increase with pinning of Pint version.
fixes:  #280

Pins Pint version

---

meta.yaml

this patches pint dependency issues.

v2022.10.1

---

src/geocat/comp/interpolation.py

- adds latex equations to `_geo_height_extrapolate` and `_temp_extrapolate`

Add rendered equations to docstrings

---

.github/workflows/ci-release.yml

Summary of changes
- I wrote the wrong command to make a conda environment and couldn't test until it was on main

Patch for import test

---

.github/workflows/ci-release.yml

Summary of change:
- add conda activate to all relevant steps

Fix the import package CI test

---

meta.yaml

This PR bumps the version number and updates the maintainer list

Version bump to v2023.02.0

---

README.md

Closes #348 
The readme was still using the anaconda badge for the NCAR channel. We are no longer releasing on that channel and are now publishing our work on the conda-forge channel. This PR updates the badge to reflect this change.
**General**

Change conda badge to conda-forge channel

---

.github/PULL_REQUEST_TEMPLATE.md

This PR fixes some typos in the PR template and lists the GeoCAT team in a way that avoids pining all of us.
Closes #Nothing I didn't open an issue for something this small.

Fix typos in PR template

---

meta.yaml

Version bump for March 2023 release

Version bump v2023.03.0

---

docs/release-notes.rst

Update release notes for v2023.03.0 and fixing some old formatting issues

Update release notes for v2023.03.0

---

src/geocat/comp/__init__.py

Closes #366 
This PR adds the `delta_pressure` wrapper (`dpres_plev`) to the `__init__.py` file so it can be imported.

Add dpres_plev init file

---

build_envs/docs.yml
build_envs/environment.yml
meta.yaml
requirements.txt

release version bump 
Closes #378

version bump 2023 03 1

---

src/geocat/comp/climatologies.py
src/geocat/comp/meteorology.py

Closes #358 
This PR updates any internal links to other functions the format ```:func: `func_name` ```
**General**
- [n/a] Request `@NCAR/geocat` for reviews

Update internal links to use sphinx internal referencing

---

.github/workflows/pypi.yaml
setup.cfg

Related to #391 
- undo 3.x -> 3.10 change tested yesterday
- switches `geocat-f2py` to `geocat.f2py` in `setup.cfg` for pypi build (can now follow the steps in `pypi.yml` successfully after reproducing the error locally and implementing these changes)
- removes an extra newline
**General**

Pypi packaging fix

---

.github/ISSUE_TEMPLATE/release.md
.github/PULL_REQUEST_TEMPLATE.md
docs/release-notes.rst

Closes #398
- updates and reformats `release.md` issue template to remove editing `meta.yaml` and adding manually triggering pypi release action
- updates `.github/PULL_REQUEST_TEMPLATE.md` to include adding a description of changes to `docs/release-notes.md`
- edits `docs/release-notes.md` to include a description of these changes
**General**

Add updating release notes to pr template

---

docs/release-notes.rst

Update release notes for v2023.06.0

---

build_envs/docs.yml
build_envs/environment.yml
docs/release-notes.rst
setup.cfg

Remove python 3.11.0 limit

---

README.md

Closes #441 
**General**
- [N/A] Add a brief summary of changes to `docs/release-notes.rst`

Rephrase README.md

---

docs/release-notes.rst
setup.cfg

Include xarray pinning in setup.cfg

---

CODE_OF_CONDUCT.md
docs/release-notes.rst

Add Code of Conduct (geocat-comp/CODE_OF_CONDUCT.md)
Closes #447 
**General**
- [N/A] Make an issue if one doesn't already exist
- [N/A] Make your changes in a forked repository rather than directly in this repo
**Functionality**
- [N/A] Function is in appropriate module file
- [N/A] New function(s) intended for public API added to `geocat/comp/__init__.py` file
**Testing**
- [N/A] Tests for function exists in associated module test file
- [N/A] Tests cover all possible logical paths in your function
**Documentation**
- [N/A] Docstrings have been added to all new functions ([Documentation Standards](https://geocat.ucar.edu/pages/contributing.html#422-documentation))
- [N/A] Docstrings have updated with any function changes
- [N/A] Internal functions have a preceding underscore (`_`) and …

CODE_OF_CONDUCT.md

---

docs/release-notes.rst

Closes #466 
**General**
- [n/a] Add a brief summary of changes to `docs/release-notes.rst`

Re-add title to release notes

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
docs/release-notes.rst

Closes #455
Changes to the PR template (`.github/PULL_REQUEST_TEMPLATE.md`):
**General**
- [n/a] Request `@NCAR/geocat` for reviews
- [n/a] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.

Update PR template

---

docs/contrib.rst
docs/release-notes.rst

Contributing Edits

---

docs/release-notes.rst

Finalize release notes for v2023.10.0

---

docs/release-notes.rst
docs/support.rst

Closes #494 
- updates link from internal sundog link to esds blog link
**General**

Update office hours link

---

build_envs/upstream-dev-environment.yml
docs/release-notes.rst

Remove Python from upstream dev CI environment file so it does unintentionally update to the latest version and break things.
Closes #435
**General**

Fix Python version in upstream CI

---

README.md
docs/release-notes.rst

Closes #493
See [README in my branch](https://github.com/anissa111/geocat-comp/blob/issue493/README.md):
**General**

Add benchmark badge to readme

---

.github/workflows/asv-benchmarking.yml
docs/release-notes.rst

Closes #498 
Adding `|| true` to the end of the `asv-run` command makes sure that we won't accidentally cancel the run when asv fails any individual benchmark.
Also, moves up the earliest tag to start benchmarking since commits before `v2023.02.0` fail on import
See on my fork for tag `v2022.10.0`, which we know will fail from [these logs](https://github.com/NCAR/geocat-comp/actions/runs/6699414577/job/18203492348)
- [This run](https://github.com/anissa111/geocat-comp/actions/runs/6700449803/job/18206404400) fails, as our benchmark CI did
- [This run](https://github.com/anissa111/geocat-comp/actions/runs/6700145959/job/18205581590#step:7:26), with the addition of `|| true`, passes and continues past the benchmark running step even though the benchmark "failed"
**General**

Don't fail workflow for expected individual benchmarks failures

---

docs/release-notes.rst

Finalize release notes for v2023.10.1

---

docs/contrib.rst
docs/release-notes.rst

Update mamba install link

---

.github/workflows/ci.yml
build_envs/docs.yml
docs/release-notes.rst

Also part of #456
- update concurrency check and cancellation
- remove unnecessary token for checkout actions
- switch linkcheck action to micromamba
- switch regular CI to micromamba
- add environment caching to regular CI and linkcheck
**General**

CI Improvements

---

ci/install-upstream.sh
docs/release-notes.rst

Closes #536
- updates nightly wheels source
- adds xarray to nightly wheels instead of source installation
**General**

Update nightly wheels source

---

docs/release-notes.rst

Update release-notes.rst for v2024.01.0

---

docs/release-notes.rst
geocat/comp/climatologies.py
test/test_climatologies.py

Update hourly frequency aliases after Pandas deprecation of 'H'.
Closes #549
**General**

Update hourly frequency aliases

---

build_envs/asv-bench.yml
docs/release-notes.rst

Temporary pinning asv

---

docs/conf.py
docs/release-notes.rst

Add stackoverflow.com/help/* links to linkcheck_ignore

---

docs/contrib.rst
docs/release-notes.rst
setup.cfg

Closes #560 
Cleans up some outdated documenation
**General**

Documentation Clean Up

---

build_envs/asv-bench.yml
docs/release-notes.rst

Re-pin ASV

---

docs/release-notes.rst

Related to #572 
**General**
- [n/a] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the next unreleased release. Possible sections include: Documentation, New Features, Bug Fixes, Internal Changes, Breaking Changes/Deprecated

Update release notes for v2024.02.0

---

.pre-commit-config.yaml
docs/contrib.rst
docs/getting-started.rst
docs/installation.rst
docs/release-notes.rst
docs/user_api/index.rst
geocat/comp/climatologies.py
geocat/comp/fourier_filters.py
geocat/comp/interpolation.py
geocat/comp/meteorology.py
pyproject.toml

pre-commit hook for codespell

---

docs/release-notes.rst
test/test_dask.py

Part of #585 
- also fixes a small formatting issue I saw
**General**
- [n/a] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the next unreleased release. Possible sections include: Documentation, New Features, Bug Fixes, Internal Changes, Breaking Changes/Deprecated

Update release notes for v2024.03.0

---

docs/release-notes.rst

Part of #585 
I'll go back and edit the tag to make sure this shows up on the tagged version of the release notes. This shouldn't affect conda-forge or pypi as the documentation is not packaged.
My bad folks 🤦‍♀️
**General**

Forgot date on release notes

---

.pre-commit-config.yaml
docs/release-notes.rst

Add autoupdate for pre-commit hook versions

---

.github/workflows/ci.yml
docs/release-notes.rst

Change CI to run on macos-latest rather than macos-14
Closes #616
**General**

CI to run macos-latest

---

.pre-commit-config.yaml
docs/release-notes.rst

Useful pre-commit hook to check that the yaml file is valid before committing
Closes #624
**General**

pre-commit hook check-yaml

---

.github/workflows/ci-release.yml
.github/workflows/ci.yml
.github/workflows/upstream-dev-ci.yml
docs/release-notes.rst

Removes the temporary micromamba pin from #645 now that issues upstream have been addressed. 
**General**

Remove temporary micromamba pin

---

docs/conf.py
docs/release-notes.rst

Fixes our documentation theme configuration.
Closes #656
**General**

Theme configuration fix

---

docs/release-notes.rst
geocat/comp/stats.py

Updates a couple of links to the eofs documentation and the corresponding descriptions.
Closes #660
**General**

Update eofs links and descriptions

---

docs/release-notes.rst
geocat/comp/meteorology.py

Link to `satvpr_slope_fao56` for `saturation_vapor_pressure_slope` documentation instead of `satvpr_temp_fao56`
Closes #672
**General**
**Documentation**

Update saturation_vapor_pressure_slope link

---

build_envs/asv-bench.yml
build_envs/environment.yml
docs/release-notes.rst
requirements.txt
setup.cfg

Pins SciPy version <1.15 following recent CI failures.
Relates to #673
**General**

SciPy version pin

---

docs/release-notes.rst

Part of #679 
Updates release notes for v2025.01.0
**General**

Update release notes for v2025.01.0

---

docs/release-notes.rst

This PR finalizes release notes for v2025.02.0
- adds proper heading, release date, and plain text summary
- corrects a PR link
- adds release notes for code of conduct updates, as changes were not added through a regular PR
- adds reusable link for Orhan
Part of #693
**General**
- [n/a] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the upcoming release.

Update release notes for v2025.02.0

---

docs/conf.py
docs/release-notes.rst

Reconfigures analytics through the theme configuration option.
Relates to NCAR/geocat-planning#16
Closes NCAR/geocat-planning#17
**General**

Reconfigure analytics

---

docs/release-notes.rst
geocat/comp/meteorology.py

No functionality changes, just adding more comments to describe where variables are being pulled from for the relative humidity equations
Related to https://github.com/NCAR/geocat-applications/issues/191 and https://github.com/NCAR/geocat-applications/issues/190
**General**

Additional RH Comments

---

CODE_OF_CONDUCT.md

Removes the duplicate heading, which I believe is a typo.

Update CODE_OF_CONDUCT.md to Fix A Small Typo

---

.github/workflows/asv-benchmarking.yml
.github/workflows/ci-release.yml
.github/workflows/ci.yml
.github/workflows/pypi.yaml
.github/workflows/upstream-dev-ci.yml
docs/release-notes.rst

Updates Third Party Github Actions to a commit hash instead of version tags
Closes #715 
**General**

Pin Third Party Github Actions

---

.pre-commit-config.yaml
docs/release-notes.rst

Adding in black to handle the .rst and .md files that are not covered by ruff
- Ignores changing strings to double quotes
Closes #705
**General**

blackdoc for .rst/.md

---

docs/release-notes.rst

This PR updates the release notes for v2025.05.0
Part of #730
**General**
- [n/a] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the upcoming release.

Update release notes for v2025.05.0

---

docs/release-notes.rst
geocat/comp/interpolation.py

Updates the link to the cartopy docs to get the link checker passing.
**General**

Update cartopy docs link

---

docs/release-notes.rst

Update release notes for v2025.09.0
Part of #756 
**General**

Update release notes for v2025.09.0

---

.github/dependabot.yml
docs/release-notes.rst

Groups Dependabot updates to minimize some of the noise associated with those
Relates to ncar/geocat-applications#244
**General**

Group Dependabot updates
